<?php


namespace Tarzan\Custom\Item;


use pocketmine\item\Item;

class SimpleItem extends Item
{
    public function __construct(int $id, int $meta, string $name, int $count)
    {
        $this->count = $count;
        parent::__construct($id, $meta, $name);
    }

    public function getCount(): int
    {
        return  $this->count; // TODO: Change the autogenerated stub
    }
}